openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
paths:
  /api/v1/login:
    post:
      summary: Login user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successfull
        "401":
          description: Missing param
        "500":
          description: Internal server error
