openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
paths:
  /login:
    post:
      summary: Đăng nhập người dùng
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Đăng nhập thành công
        "401":
          description: Sai tên đăng nhập hoặc mật khẩu
        "500":
          description: Lỗi server
